parameters:
#    annonce.example.class: Annonces\AnnoncesBundle\Example

services:
#    annonce.example:
#        class: %annonce.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
