parameters:
#    utilisateur.example.class: Utilisateur\UtilisateurBundle\Example

services:
#    utilisateur.example:
#        class: %utilisateur.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
