<?php

namespace Proxies\__CG__\Utilisateur\UtilisateurBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Metier extends \Utilisateur\UtilisateurBundle\Entity\Metier implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Metier' . "\0" . 'idMetier', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Metier' . "\0" . 'titreMetier', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Metier' . "\0" . 'idligneoffre');
        }

        return array('__isInitialized__', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Metier' . "\0" . 'idMetier', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Metier' . "\0" . 'titreMetier', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Metier' . "\0" . 'idligneoffre');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Metier $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdMetier()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdMetier();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdMetier', array());

        return parent::getIdMetier();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitreMetier($titreMetier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitreMetier', array($titreMetier));

        return parent::setTitreMetier($titreMetier);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitreMetier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitreMetier', array());

        return parent::getTitreMetier();
    }

    /**
     * {@inheritDoc}
     */
    public function addIdligneoffre(\Utilisateur\UtilisateurBundle\Entity\Offre $idligneoffre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIdligneoffre', array($idligneoffre));

        return parent::addIdligneoffre($idligneoffre);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIdligneoffre(\Utilisateur\UtilisateurBundle\Entity\Offre $idligneoffre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIdligneoffre', array($idligneoffre));

        return parent::removeIdligneoffre($idligneoffre);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdligneoffre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdligneoffre', array());

        return parent::getIdligneoffre();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
