<?php

namespace Proxies\__CG__\Utilisateur\UtilisateurBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CandidatExperienceNiveau extends \Utilisateur\UtilisateurBundle\Entity\CandidatExperienceNiveau implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\CandidatExperienceNiveau' . "\0" . 'idCandidatExperienceNiveau', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\CandidatExperienceNiveau' . "\0" . 'idCandidat', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\CandidatExperienceNiveau' . "\0" . 'idExperience', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\CandidatExperienceNiveau' . "\0" . 'idNiveauExperience');
        }

        return array('__isInitialized__', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\CandidatExperienceNiveau' . "\0" . 'idCandidatExperienceNiveau', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\CandidatExperienceNiveau' . "\0" . 'idCandidat', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\CandidatExperienceNiveau' . "\0" . 'idExperience', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\CandidatExperienceNiveau' . "\0" . 'idNiveauExperience');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CandidatExperienceNiveau $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdCandidatExperienceNiveau()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdCandidatExperienceNiveau();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCandidatExperienceNiveau', array());

        return parent::getIdCandidatExperienceNiveau();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCandidat(\Utilisateur\UtilisateurBundle\Entity\Candidat $idCandidat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCandidat', array($idCandidat));

        return parent::setIdCandidat($idCandidat);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCandidat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCandidat', array());

        return parent::getIdCandidat();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdExperience(\Utilisateur\UtilisateurBundle\Entity\Experience $idExperience)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdExperience', array($idExperience));

        return parent::setIdExperience($idExperience);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdExperience()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdExperience', array());

        return parent::getIdExperience();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdNiveauExperience(\Utilisateur\UtilisateurBundle\Entity\NvieauExperience $idNiveauExperience)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdNiveauExperience', array($idNiveauExperience));

        return parent::setIdNiveauExperience($idNiveauExperience);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdNiveauExperience()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdNiveauExperience', array());

        return parent::getIdNiveauExperience();
    }

}
