<?php

namespace Proxies\__CG__\Utilisateur\UtilisateurBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Experience extends \Utilisateur\UtilisateurBundle\Entity\Experience implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Experience' . "\0" . 'idExperience', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Experience' . "\0" . 'candidatNE', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Experience' . "\0" . 'titreExperience', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Experience' . "\0" . 'dateDebutExperience', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Experience' . "\0" . 'dateFinExperience', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Experience' . "\0" . 'fonction', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Experience' . "\0" . 'nombreMois', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Experience' . "\0" . 'competenceUtilisees', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Experience' . "\0" . 'entrepriseExperience', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Experience' . "\0" . 'lieuExperience', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Experience' . "\0" . 'descriptionExperience');
        }

        return array('__isInitialized__', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Experience' . "\0" . 'idExperience', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Experience' . "\0" . 'candidatNE', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Experience' . "\0" . 'titreExperience', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Experience' . "\0" . 'dateDebutExperience', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Experience' . "\0" . 'dateFinExperience', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Experience' . "\0" . 'fonction', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Experience' . "\0" . 'nombreMois', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Experience' . "\0" . 'competenceUtilisees', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Experience' . "\0" . 'entrepriseExperience', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Experience' . "\0" . 'lieuExperience', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Experience' . "\0" . 'descriptionExperience');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Experience $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdExperience()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdExperience();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdExperience', array());

        return parent::getIdExperience();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitreExperience($titreExperience)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitreExperience', array($titreExperience));

        return parent::setTitreExperience($titreExperience);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitreExperience()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitreExperience', array());

        return parent::getTitreExperience();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDebutExperience($dateDebutExperience)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDebutExperience', array($dateDebutExperience));

        return parent::setDateDebutExperience($dateDebutExperience);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDebutExperience()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDebutExperience', array());

        return parent::getDateDebutExperience();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFinExperience($dateFinExperience)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFinExperience', array($dateFinExperience));

        return parent::setDateFinExperience($dateFinExperience);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFinExperience()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFinExperience', array());

        return parent::getDateFinExperience();
    }

    /**
     * {@inheritDoc}
     */
    public function setFonction($fonction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFonction', array($fonction));

        return parent::setFonction($fonction);
    }

    /**
     * {@inheritDoc}
     */
    public function getFonction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFonction', array());

        return parent::getFonction();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreMois($nombreMois)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreMois', array($nombreMois));

        return parent::setNombreMois($nombreMois);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreMois()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreMois', array());

        return parent::getNombreMois();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompetenceUtilisees($competenceUtilisees)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompetenceUtilisees', array($competenceUtilisees));

        return parent::setCompetenceUtilisees($competenceUtilisees);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompetenceUtilisees()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompetenceUtilisees', array());

        return parent::getCompetenceUtilisees();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntrepriseExperience($entrepriseExperience)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntrepriseExperience', array($entrepriseExperience));

        return parent::setEntrepriseExperience($entrepriseExperience);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntrepriseExperience()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntrepriseExperience', array());

        return parent::getEntrepriseExperience();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieuExperience($lieuExperience)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieuExperience', array($lieuExperience));

        return parent::setLieuExperience($lieuExperience);
    }

    /**
     * {@inheritDoc}
     */
    public function getLieuExperience()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieuExperience', array());

        return parent::getLieuExperience();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionExperience($descriptionExperience)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionExperience', array($descriptionExperience));

        return parent::setDescriptionExperience($descriptionExperience);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionExperience()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionExperience', array());

        return parent::getDescriptionExperience();
    }

    /**
     * {@inheritDoc}
     */
    public function addCandidatNE(\Utilisateur\UtilisateurBundle\Entity\CandidatExperienceNiveau $candidatNE)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCandidatNE', array($candidatNE));

        return parent::addCandidatNE($candidatNE);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCandidatNE(\Utilisateur\UtilisateurBundle\Entity\CandidatExperienceNiveau $candidatNE)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCandidatNE', array($candidatNE));

        return parent::removeCandidatNE($candidatNE);
    }

    /**
     * {@inheritDoc}
     */
    public function getCandidatNE()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCandidatNE', array());

        return parent::getCandidatNE();
    }

}
