<?php

namespace Proxies\__CG__\Utilisateur\UtilisateurBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Formation extends \Utilisateur\UtilisateurBundle\Entity\Formation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Formation' . "\0" . 'idFormation', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Formation' . "\0" . 'nomFormation', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Formation' . "\0" . 'diplome', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Formation' . "\0" . 'lieuFormation', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Formation' . "\0" . 'etablissementFormation', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Formation' . "\0" . 'descriptionFormation', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Formation' . "\0" . 'dateDebutFormation', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Formation' . "\0" . 'dateFinFormation', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Formation' . "\0" . 'idCandidat');
        }

        return array('__isInitialized__', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Formation' . "\0" . 'idFormation', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Formation' . "\0" . 'nomFormation', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Formation' . "\0" . 'diplome', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Formation' . "\0" . 'lieuFormation', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Formation' . "\0" . 'etablissementFormation', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Formation' . "\0" . 'descriptionFormation', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Formation' . "\0" . 'dateDebutFormation', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Formation' . "\0" . 'dateFinFormation', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Formation' . "\0" . 'idCandidat');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Formation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdFormation()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdFormation();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdFormation', array());

        return parent::getIdFormation();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomFormation($nomFormation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomFormation', array($nomFormation));

        return parent::setNomFormation($nomFormation);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomFormation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomFormation', array());

        return parent::getNomFormation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiplome($diplome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiplome', array($diplome));

        return parent::setDiplome($diplome);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiplome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiplome', array());

        return parent::getDiplome();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieuFormation($lieuFormation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieuFormation', array($lieuFormation));

        return parent::setLieuFormation($lieuFormation);
    }

    /**
     * {@inheritDoc}
     */
    public function getLieuFormation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieuFormation', array());

        return parent::getLieuFormation();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtablissementFormation($etablissementFormation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtablissementFormation', array($etablissementFormation));

        return parent::setEtablissementFormation($etablissementFormation);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtablissementFormation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtablissementFormation', array());

        return parent::getEtablissementFormation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionFormation($descriptionFormation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionFormation', array($descriptionFormation));

        return parent::setDescriptionFormation($descriptionFormation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionFormation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionFormation', array());

        return parent::getDescriptionFormation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDebutFormation($dateDebutFormation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDebutFormation', array($dateDebutFormation));

        return parent::setDateDebutFormation($dateDebutFormation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDebutFormation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDebutFormation', array());

        return parent::getDateDebutFormation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFinFormation($dateFinFormation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFinFormation', array($dateFinFormation));

        return parent::setDateFinFormation($dateFinFormation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFinFormation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFinFormation', array());

        return parent::getDateFinFormation();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCandidat(\Utilisateur\UtilisateurBundle\Entity\Candidat $idCandidat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCandidat', array($idCandidat));

        return parent::setIdCandidat($idCandidat);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCandidat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCandidat', array());

        return parent::getIdCandidat();
    }

}
