<?php

namespace Proxies\__CG__\Utilisateur\UtilisateurBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Offre extends \Utilisateur\UtilisateurBundle\Entity\Offre implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Offre' . "\0" . 'ligneOffre', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Offre' . "\0" . 'lidOffre', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Offre' . "\0" . 'idEntreprise', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Offre' . "\0" . 'idTypeOffre', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Offre' . "\0" . 'activation');
        }

        return array('__isInitialized__', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Offre' . "\0" . 'ligneOffre', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Offre' . "\0" . 'lidOffre', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Offre' . "\0" . 'idEntreprise', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Offre' . "\0" . 'idTypeOffre', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Offre' . "\0" . 'activation');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Offre $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getLidOffre()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getLidOffre();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLidOffre', array());

        return parent::getLidOffre();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEntreprise(\Utilisateur\UtilisateurBundle\Entity\Entreprise $idEntreprise = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEntreprise', array($idEntreprise));

        return parent::setIdEntreprise($idEntreprise);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEntreprise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEntreprise', array());

        return parent::getIdEntreprise();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTypeOffre(\Utilisateur\UtilisateurBundle\Entity\TypeOffre $idTypeOffre = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTypeOffre', array($idTypeOffre));

        return parent::setIdTypeOffre($idTypeOffre);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTypeOffre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTypeOffre', array());

        return parent::getIdTypeOffre();
    }

    /**
     * {@inheritDoc}
     */
    public function addLigneOffre(\Utilisateur\UtilisateurBundle\Entity\LigneOffre $ligneoffre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLigneOffre', array($ligneoffre));

        return parent::addLigneOffre($ligneoffre);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLigneOffre(\Utilisateur\UtilisateurBundle\Entity\LigneOffre $ligneoffre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLigneOffre', array($ligneoffre));

        return parent::removeLigneOffre($ligneoffre);
    }

    /**
     * {@inheritDoc}
     */
    public function getLigneOffre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLigneOffre', array());

        return parent::getLigneOffre();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivation($activation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivation', array($activation));

        return parent::setActivation($activation);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivation', array());

        return parent::getActivation();
    }

}
