<?php

namespace Proxies\__CG__\Utilisateur\UtilisateurBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Candidat extends \Utilisateur\UtilisateurBundle\Entity\Candidat implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Candidat' . "\0" . 'idCandidat', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Candidat' . "\0" . 'nomCandidat', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Candidat' . "\0" . 'utilisateur', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Candidat' . "\0" . 'prenom', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Candidat' . "\0" . 'adresse', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Candidat' . "\0" . 'civlite', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Candidat' . "\0" . 'situationFamliliale', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Candidat' . "\0" . 'site', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Candidat' . "\0" . 'telephone', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Candidat' . "\0" . 'photo', 'file', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Candidat' . "\0" . 'idVille', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Candidat' . "\0" . 'idStatutActuel', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Candidat' . "\0" . 'idNiveauEtudes', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Candidat' . "\0" . 'idOffreLigneOffre');
        }

        return array('__isInitialized__', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Candidat' . "\0" . 'idCandidat', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Candidat' . "\0" . 'nomCandidat', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Candidat' . "\0" . 'utilisateur', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Candidat' . "\0" . 'prenom', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Candidat' . "\0" . 'adresse', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Candidat' . "\0" . 'civlite', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Candidat' . "\0" . 'situationFamliliale', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Candidat' . "\0" . 'site', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Candidat' . "\0" . 'telephone', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Candidat' . "\0" . 'photo', 'file', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Candidat' . "\0" . 'idVille', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Candidat' . "\0" . 'idStatutActuel', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Candidat' . "\0" . 'idNiveauEtudes', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\Candidat' . "\0" . 'idOffreLigneOffre');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Candidat $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdCandidat()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdCandidat();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCandidat', array());

        return parent::getIdCandidat();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomCandidat($nomCandidat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomCandidat', array($nomCandidat));

        return parent::setNomCandidat($nomCandidat);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomCandidat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomCandidat', array());

        return parent::getNomCandidat();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', array($prenom));

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', array());

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', array($adresse));

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', array());

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setCivlite($civlite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCivlite', array($civlite));

        return parent::setCivlite($civlite);
    }

    /**
     * {@inheritDoc}
     */
    public function getCivlite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCivlite', array());

        return parent::getCivlite();
    }

    /**
     * {@inheritDoc}
     */
    public function setSituationFamliliale($situationFamliliale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSituationFamliliale', array($situationFamliliale));

        return parent::setSituationFamliliale($situationFamliliale);
    }

    /**
     * {@inheritDoc}
     */
    public function getSituationFamliliale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSituationFamliliale', array());

        return parent::getSituationFamliliale();
    }

    /**
     * {@inheritDoc}
     */
    public function setSite($site)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSite', array($site));

        return parent::setSite($site);
    }

    /**
     * {@inheritDoc}
     */
    public function getSite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSite', array());

        return parent::getSite();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone($telephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', array($telephone));

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', array());

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto($photo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', array($photo));

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', array());

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdVille(\Utilisateur\UtilisateurBundle\Entity\Ville $idVille = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdVille', array($idVille));

        return parent::setIdVille($idVille);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdVille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdVille', array());

        return parent::getIdVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdStatutActuel(\Utilisateur\UtilisateurBundle\Entity\StatutActuel $idStatutActuel = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdStatutActuel', array($idStatutActuel));

        return parent::setIdStatutActuel($idStatutActuel);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdStatutActuel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdStatutActuel', array());

        return parent::getIdStatutActuel();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdNiveauEtudes(\Utilisateur\UtilisateurBundle\Entity\NiveauEtudes $idNiveauEtudes = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdNiveauEtudes', array($idNiveauEtudes));

        return parent::setIdNiveauEtudes($idNiveauEtudes);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdNiveauEtudes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdNiveauEtudes', array());

        return parent::getIdNiveauEtudes();
    }

    /**
     * {@inheritDoc}
     */
    public function addIdOffreLigneOffre(\Utilisateur\UtilisateurBundle\Entity\LigneOffre $idOffreLigneOffre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIdOffreLigneOffre', array($idOffreLigneOffre));

        return parent::addIdOffreLigneOffre($idOffreLigneOffre);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIdOffreLigneOffre(\Utilisateur\UtilisateurBundle\Entity\LigneOffre $idOffreLigneOffre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIdOffreLigneOffre', array($idOffreLigneOffre));

        return parent::removeIdOffreLigneOffre($idOffreLigneOffre);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdOffreLigneOffre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdOffreLigneOffre', array());

        return parent::getIdOffreLigneOffre();
    }

    /**
     * {@inheritDoc}
     */
    public function setUtilisateur(\Utilisateur\UtilisateurBundle\Entity\Utilisateur $utilisateur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUtilisateur', array($utilisateur));

        return parent::setUtilisateur($utilisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtilisateur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtilisateur', array());

        return parent::getUtilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getAbsolutePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsolutePath', array());

        return parent::getAbsolutePath();
    }

    /**
     * {@inheritDoc}
     */
    public function getWebPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebPath', array());

        return parent::getWebPath();
    }

    /**
     * {@inheritDoc}
     */
    public function preUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpload', array());

        return parent::preUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function upload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'upload', array());

        return parent::upload();
    }

    /**
     * {@inheritDoc}
     */
    public function removeUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUpload', array());

        return parent::removeUpload();
    }

}
