<?php

namespace Proxies\__CG__\Utilisateur\UtilisateurBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LigneOffre extends \Utilisateur\UtilisateurBundle\Entity\LigneOffre implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\LigneOffre' . "\0" . 'idOffreLigneOffre', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\LigneOffre' . "\0" . 'idCandidat', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\LigneOffre' . "\0" . 'titreOffre', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\LigneOffre' . "\0" . 'idMetier', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\LigneOffre' . "\0" . 'descriptionPoste', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\LigneOffre' . "\0" . 'descriptionProfileRecherche', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\LigneOffre' . "\0" . 'piecesADeposer', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\LigneOffre' . "\0" . 'candidateurEnLigne', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\LigneOffre' . "\0" . 'dateLimiteOffre', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\LigneOffre' . "\0" . 'dateAjoutOffre', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\LigneOffre' . "\0" . 'dateModificationOffre', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\LigneOffre' . "\0" . 'exigences', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\LigneOffre' . "\0" . 'lidOffre');
        }

        return array('__isInitialized__', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\LigneOffre' . "\0" . 'idOffreLigneOffre', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\LigneOffre' . "\0" . 'idCandidat', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\LigneOffre' . "\0" . 'titreOffre', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\LigneOffre' . "\0" . 'idMetier', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\LigneOffre' . "\0" . 'descriptionPoste', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\LigneOffre' . "\0" . 'descriptionProfileRecherche', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\LigneOffre' . "\0" . 'piecesADeposer', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\LigneOffre' . "\0" . 'candidateurEnLigne', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\LigneOffre' . "\0" . 'dateLimiteOffre', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\LigneOffre' . "\0" . 'dateAjoutOffre', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\LigneOffre' . "\0" . 'dateModificationOffre', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\LigneOffre' . "\0" . 'exigences', '' . "\0" . 'Utilisateur\\UtilisateurBundle\\Entity\\LigneOffre' . "\0" . 'lidOffre');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (LigneOffre $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdOffreLigneOffre()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdOffreLigneOffre();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdOffreLigneOffre', array());

        return parent::getIdOffreLigneOffre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitreOffre($titreOffre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitreOffre', array($titreOffre));

        return parent::setTitreOffre($titreOffre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitreOffre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitreOffre', array());

        return parent::getTitreOffre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionPoste($descriptionPoste)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionPoste', array($descriptionPoste));

        return parent::setDescriptionPoste($descriptionPoste);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionPoste()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionPoste', array());

        return parent::getDescriptionPoste();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionProfileRecherche($descriptionProfileRecherche)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionProfileRecherche', array($descriptionProfileRecherche));

        return parent::setDescriptionProfileRecherche($descriptionProfileRecherche);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionProfileRecherche()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionProfileRecherche', array());

        return parent::getDescriptionProfileRecherche();
    }

    /**
     * {@inheritDoc}
     */
    public function setPiecesADeposer($piecesADeposer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPiecesADeposer', array($piecesADeposer));

        return parent::setPiecesADeposer($piecesADeposer);
    }

    /**
     * {@inheritDoc}
     */
    public function getPiecesADeposer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPiecesADeposer', array());

        return parent::getPiecesADeposer();
    }

    /**
     * {@inheritDoc}
     */
    public function setCandidateurEnLigne($candidateurEnLigne)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCandidateurEnLigne', array($candidateurEnLigne));

        return parent::setCandidateurEnLigne($candidateurEnLigne);
    }

    /**
     * {@inheritDoc}
     */
    public function getCandidateurEnLigne()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCandidateurEnLigne', array());

        return parent::getCandidateurEnLigne();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateLimiteOffre($dateLimiteOffre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateLimiteOffre', array($dateLimiteOffre));

        return parent::setDateLimiteOffre($dateLimiteOffre);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateLimiteOffre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateLimiteOffre', array());

        return parent::getDateLimiteOffre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAjoutOffre($dateAjoutOffre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAjoutOffre', array($dateAjoutOffre));

        return parent::setDateAjoutOffre($dateAjoutOffre);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAjoutOffre($format = 'Y-m-d H:i:s')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAjoutOffre', array($format));

        return parent::getDateAjoutOffre($format);
    }

    /**
     * {@inheritDoc}
     */
    public function setDateModificationOffre($dateModificationOffre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateModificationOffre', array($dateModificationOffre));

        return parent::setDateModificationOffre($dateModificationOffre);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateModificationOffre($format = 'Y-m-d H:i:s')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateModificationOffre', array($format));

        return parent::getDateModificationOffre($format);
    }

    /**
     * {@inheritDoc}
     */
    public function setExigences($exigences)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExigences', array($exigences));

        return parent::setExigences($exigences);
    }

    /**
     * {@inheritDoc}
     */
    public function getExigences()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExigences', array());

        return parent::getExigences();
    }

    /**
     * {@inheritDoc}
     */
    public function setLidOffre(\Utilisateur\UtilisateurBundle\Entity\Offre $lidOffre = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLidOffre', array($lidOffre));

        return parent::setLidOffre($lidOffre);
    }

    /**
     * {@inheritDoc}
     */
    public function getLidOffre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLidOffre', array());

        return parent::getLidOffre();
    }

    /**
     * {@inheritDoc}
     */
    public function addIdMetier(\Utilisateur\UtilisateurBundle\Entity\Metier $idMetier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIdMetier', array($idMetier));

        return parent::addIdMetier($idMetier);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIdMetier(\Utilisateur\UtilisateurBundle\Entity\Metier $idMetier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIdMetier', array($idMetier));

        return parent::removeIdMetier($idMetier);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdMetier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdMetier', array());

        return parent::getIdMetier();
    }

    /**
     * {@inheritDoc}
     */
    public function addIdCandidat(\Utilisateur\UtilisateurBundle\Entity\Candidat $idCandidat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIdCandidat', array($idCandidat));

        return parent::addIdCandidat($idCandidat);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIdCandidat(\Utilisateur\UtilisateurBundle\Entity\Candidat $idCandidat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIdCandidat', array($idCandidat));

        return parent::removeIdCandidat($idCandidat);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCandidat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCandidat', array());

        return parent::getIdCandidat();
    }

}
